meson: Fix the nghttp2 fallback
Which previously failed due to compiler.has_function() throwing:

    ERROR: Dependencies must be external dependencies